### ISSUE TITLE
Bluetooth Headset didn't work 

### ISSUE THREAD

**Issue by alps2006** [HappyZ/dpt-tools#171]
First thanks for your work.  

I flashed `flashable_bluetooth_hid pkg`, but  Bluetooth Headset didn't work  after connected successfully .
I caught some log with `logcat`,  there was a lot of error. 

```
05-30 17:09:19.695 E/ExoPlayerImplInternal( 3700): Internal runtime error.

05-30 17:09:19.695 E/ExoPlayerImplInternal( 3700): java.lang.IllegalStateException

05-30 17:09:19.695 E/ExoPlayerImplInternal( 3700): 	at android.media.MediaCodec.releaseOutputBuffer(Native Method)

...

05-30 17:09:19.696 W/System.err( 3700): com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException

05-30 17:09:19.698 E/ExoPlayerImplInternal( 3700): Disable failed.

05-30 17:09:19.698 E/ExoPlayerImplInternal( 3700): java.lang.IllegalStateException

05-30 17:09:19.698 E/ExoPlayerImplInternal( 3700): 	at android.media.MediaCodec.native_flush(Native Method)

05-30 17:09:19.698 E/ExoPlayerImplInternal( 3700): 	at android.media.MediaCodec.flush(MediaCodec.java:662)
...
05-30 17:09:22.928 F/libc    (17644): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 17651 (AudioOut_2)

05-30 17:09:22.932 F/DEBUG   ( 1653): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

05-30 17:09:22.932 F/DEBUG   ( 1653): Build fingerprint: 'Sony/FPX_1010/FPX-1010:1.6.03.09261/LMY47V/09261219:user/test-keys'

05-30 17:09:22.932 F/DEBUG   ( 1653): Revision: '0'

05-30 17:09:22.932 F/DEBUG   ( 1653): ABI: 'arm'

05-30 17:09:22.933 F/DEBUG   ( 1653): pid: 17644, tid: 17651, name: AudioOut_2  >>> /system/bin/mediaserver <<<

05-30 17:09:22.933 F/DEBUG   ( 1653): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc

05-30 17:09:22.936 W/NativeCrashListener( 2138): Couldn't find ProcessRecord for pid 17644
'''

**Comment by HappyZ** [comment]
I don't think bluetooth audio sharing works at least I've never had success..

**Comment by alps2006** [comment]
Many Roms of Taobao work well .  I think them add driver to support.

**Comment by seanlvjie** [comment]
这个包装上，可以支持蓝牙翻页器吗

**Comment by HappyZ** [comment]
I don't plan to look more into bluetooth.
