### ISSUE TITLE
Kindle crash

### ISSUE THREAD

**Issue by sisyphose** [HappyZ/dpt-tools#40]
As everyone knows, Kindle is an important application after dpt cracking, but after I install Kindle, it will crash when turning pages. Do anyone have this problem?

**Comment by HappyZ** [comment]
I can't test but which system image you are using? The taobao one or official, or https://github.com/HappyZ/dpt-tools/issues/37? It would be good to specify this.

Also, you can check `adb logcat` for more details on why it crashes.

**Comment by sisyphose** [comment]
It is sad that  hear your dpt is bricked.  I hope those who have succeeded in cracking can donate to you like me.
the  #37 and  #36 and official img both crash. i have cracked three dpt and all will crash when use kindle. but taobao'crack won't crash (Taobao service  cracked, not our crack use taobao img）.
It's weried.
it  crash when flipping pages of your own uploaded book，but when read the book purchased from Amazon it will work well. Weried!!!
I can buy you a new dpt at a 20% discount on Amazon. If you need it, please contact me.
Thank you very much for your work.

**Comment by HappyZ** [comment]
@sisyphose haha, thanks. I guess if I can open a taobao store then..., jk. I do this for fun. Taking the risk of bricking the device is part of the plan, but I do not plan to buy another with much extra cost. I will see if shankerzhiwu can fix it. Thanks for all your donation to let me ship it internationally to him :)

**Comment by sisyphose** [comment]
Well I open a taobao store...
Haha, are u chinese?

**Comment by HappyZ** [comment]
oh interesting.. good for you :) we can chat offline you can email me at yz at 9pm.me
always nice to make new friends

**Comment by ziegfeld** [comment]
@sisyphose hiya, very nice for your work and help to HappyZ!
1. Is it the official version of kindle you are using? which version? I will try myself whever I got a chance.
2. Please try this version if you have Bandu Netdisk: (credits to @p4s2wd, reportedly stable):      https://pan.baidu.com/s/1B6b-J_0YiEKf21xEZqtSOw 
  Also these 2 versions which might be optimized by Taobao: http://182.254.232.41/apptest/SONY/
  Kindle_8.0.0.68.apk	2018-Oct-29 16:30:56	57.5M	application/vnd.android.package-archive
  Kindle_V8.11.0.57.apk	2018-Nov-16 10:56:43	54.9M	application/vnd.android.package-archive

3. does all your book reading crashes when turning page? People from a Chinese bbs either reporting that behavior for non-amazon books (i.e. books from Amazon store works fine), or got this fixed already.
I will try to get more info for you.

**Comment by sisyphose** [comment]
> @sisyphose hiya, very nice for your work and help to HappyZ!
> 
> 1. Is it the official version of kindle you are using? which version? I will try myself whever I got a chance.
> 2. Please try this version if you have Bandu Netdisk: (credits to @p4s2wd, reportedly stable):      https://pan.baidu.com/s/1B6b-J_0YiEKf21xEZqtSOw
>    Also these 2 versions which might be optimized by Taobao: http://182.254.232.41/apptest/SONY/
>    Kindle_8.0.0.68.apk	2018-Oct-29 16:30:56	57.5M	application/vnd.android.package-archive
>    Kindle_V8.11.0.57.apk	2018-Nov-16 10:56:43	54.9M	application/vnd.android.package-archive
> 3. does all your book reading crashes when turning page? People from a Chinese bbs either reporting that behavior for non-amazon books (i.e. books from Amazon store works fine), or got this fixed already.
>    I will try to get more info for you.
As i have cracked four devices:
1. Every version I had tryed， all crash.
2. All  crash
3.books from Amazon store works fine. Non-amazon books will crash.
Thank u for your tips.I think it's the Kindle's page turning logic that triggered the bug, but only the non-Amazon store book crash, weried.

**Comment by ziegfeld** [comment]
> > @sisyphose hiya, very nice for your work and help to HappyZ!
> > 
> > 1. Is it the official version of kindle you are using? which version? I will try myself whever I got a chance.
> > 2. Please try this version if you have Bandu Netdisk: (credits to @p4s2wd, reportedly stable):      https://pan.baidu.com/s/1B6b-J_0YiEKf21xEZqtSOw
> >    Also these 2 versions which might be optimized by Taobao: http://182.254.232.41/apptest/SONY/
> >    Kindle_8.0.0.68.apk	2018-Oct-29 16:30:56	57.5M	application/vnd.android.package-archive
> >    Kindle_V8.11.0.57.apk	2018-Nov-16 10:56:43	54.9M	application/vnd.android.package-archive
> > 3. does all your book reading crashes when turning page? People from a Chinese bbs either reporting that behavior for non-amazon books (i.e. books from Amazon store works fine), or got this fixed already.
> >    I will try to get more info for you.
> >    As i have cracked four devices:
> 
> 1. Every version I had tryed， all crash.
> 2. All  crash
>    3.books from Amazon store works fine. Non-amazon books will crash.
>    Thank u for your tips.I think it's the Kindle's page turning logic that triggered the bug, but only the non-Amazon store book crash, weried.

No problem.
I guess I can only suggest AlReader now. It's power-saving and all-format supporting. Download from [apkpure.com](https://apkpure.com/alreader-any-text-book-reader/com.neverland.alreader)

**Comment by sh-miller** [comment]
the [MonnReader](  http://www.moondownload.com/) +     works   well

**Comment by ultraboy** [comment]
Hi, I'm using #37 system.img, the newest boot.img and Chinese local, Kindle crash too.

W/LaunchApplication_LaunchMenuPresenter( 2892): launch: title[Kindle阅读]
W/ExtensionManagerService( 2141): call launch:[ac61]
W/ExtensionManagerService( 2141): Entry [com.sony.capas.services.extension.LauncherEntry@2f19eb07]
W/ExtensionManagerService( 2141): Scheme:intent
W/ContextImpl( 2141): Calling a method in the system process without a qualified user: android.app.ContextImpl.startActivity:1233 com.sony.capas.services.extension.Launcher.launch:35 com.sony.capas.services.ExtensionManagerService.launch:68 com.sony.capas.services.IExtensionManager$Stub.onTransact:60 android.os.Binder.execTransact:446
W/ContextImpl( 2141): Calling a method in the system process without a qualified user: android.app.ContextImpl.startActivity:1245 android.app.ContextImpl.startActivity:1234 com.sony.capas.services.extension.Launcher.launch:35 com.sony.capas.services.ExtensionManagerService.launch:68 com.sony.capas.services.IExtensionManager$Stub.onTransact:60
W/ActivityManager( 2141): START u0 {act=android.intent.action.VIEW flg=0x10000000 cmp=com.amazon.kindlefc/com.amazon.kindle.UpgradePage} from uid 1000 on display 0
E/JavaBinder( 2141): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
E/JavaBinder( 2141): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.amazon.kindlefc/com.amazon.kindle.UpgradePage}; have you declared this activity in your AndroidManifest.xml?
E/JavaBinder( 2141): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
E/JavaBinder( 2141): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
E/JavaBinder( 2141): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1252)
E/JavaBinder( 2141): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1234)
E/JavaBinder( 2141): 	at com.sony.capas.services.extension.Launcher.launch(Launcher.java:35)
E/JavaBinder( 2141): 	at com.sony.capas.services.ExtensionManagerService.launch(ExtensionManagerService.java:68)
E/JavaBinder( 2141): 	at com.sony.capas.services.IExtensionManager$Stub.onTransact(IExtensionManager.java:60)
E/JavaBinder( 2141): 	at android.os.Binder.execTransact(Binder.java:446)
W/LaunchApplication_LaunchViewService( 2892): destroy:

**Comment by ultraboy** [comment]
Install a new kindle, works fine.

**Comment by sisyphose** [comment]
> Install a new kindle, works fine.

which version kindle？ I install some versions of kindle，both crash when read non-store book.

**Comment by ultraboy** [comment]
Kindle_V8.11.0.57.apk from http://182.254.232.41/apptest/SONY/
Sorry, I only read one book from kindle store. Don't know if it will crash when reading non-store book.

**Comment by ghostwheel** [comment]
For me kindle crashes when I try to read nytimes once I go into table of contents, then look at an article, kindle crashes. I think when I flip from the first page.

**Comment by sisyphose** [comment]
> Kindle_V8.11.0.57.apk from http://182.254.232.41/apptest/SONY/
> Sorry, I only read one book from kindle store. Don't know if it will crash when reading non-store book.

Today I found that  book from kindle store would crash too，the only difference is that it can  flip  two pages before crash.

**Comment by HappyZ** [comment]
looks like it crashes because
```
E/JavaBinder( 2141): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.amazon.kindlefc/com.amazon.kindle.UpgradePage}; have you declared this activity in your AndroidManifest.xml?
```
you can try to disable upgrade functions.

**Comment by sisyphose** [comment]
> looks like it crashes because
> 
> ```
> E/JavaBinder( 2141): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.amazon.kindlefc/com.amazon.kindle.UpgradePage}; have you declared this activity in your AndroidManifest.xml?
> ```
> you can try to disable upgrade functions.

Is there a simple  code? Or I will give up. Thank you

**Comment by HappyZ** [comment]
> > looks like it crashes because
> > ```
> > E/JavaBinder( 2141): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.amazon.kindlefc/com.amazon.kindle.UpgradePage}; have you declared this activity in your AndroidManifest.xml?
> > ```
> > you can try to disable upgrade functions.
> 
> Is there a simple code? Or I will give up. Thank you

Not really. This is my guess. If in the app, there's a setting on automatic upgrade, disable it. 

Another guess is if you turn off WiFi, it will not be able to check upgrade.

The best would be modifying kindle app and avoid the upgrade activity.

**Comment by yefeiyu** [comment]
The Kindle app will crash if I open any SAMPLE book.

**Comment by Yanjunhui** [comment]
![1553778333078](https://user-images.githubusercontent.com/8891191/55159997-43c1cb00-519d-11e9-8a83-97fd8fa28685.jpg)
I've shut down all updates and downloads. Now it's still crashing. I find a rule: if it's not an official book, it crashes when it turns pages. I wonder if I can't create crashes caused by reading progress. See pictures for specific error messages.

```
W/ContextImpl(10862): Failed to ensure directory: /storage/external/Android/data/com.amazon.kindle/files
```

This directory is read-only. I can't make the dir.

```
mkdir -p /storage/external/Android/data/com.amazon.kindle/files  
mkdir failed for /storage/external/Android/, Read-only file system
```

**Comment by fz68** [comment]
It's wierd that comic books pushed by http://vol.moe is OK, no crash.

**Comment by huhd** [comment]
<pre>CrashType: data_app_crash                                                                                                           
ContentType: ThirdPartyJavaCrash                                                                                     
Process: com.amazon.kindle                                                                                                          
Version: 8.11.0.57                                                                                                                       
OsBuildNumber: 876                                                                                                                  
                                                                                                                                                               
java.lang.NullPointerException: Attempt to invoke virtual method &apos;boolean android.view.animation.Animation.hasStarted()&apos; on a null object reference
        at com.amazon.android.docviewer.animation.AnimationTranslateX.start(AnimationTranslateX.java:30)                                 
        at com.amazon.android.docviewer.mobi.AnimatedPageFlipper.startAnimation(AnimatedPageFlipper.java:232)                       
        at com.amazon.android.docviewer.mobi.MobiView.onLayout(MobiView.java:444)                                                   
        at android.view.View.layout(View.java:15804)                                                                                     
        at android.view.ViewGroup.layout(ViewGroup.java:5060)                                                                            
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)                                                          
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)                                                                     
        at android.view.View.layout(View.java:15804)                                                                                     
        at android.view.ViewGroup.layout(ViewGroup.java:5060)                                                                       
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)                                                          
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)                                                                     
        at android.view.View.layout(View.java:15804)                     </pre>

**Comment by yanjunhui** [comment]
> It's wierd that comic books pushed by http://vol.moe is OK, no crash.

文字比较多的就容易崩溃

**Comment by yefeiyu** [comment]
较大的文件也崩溃

**Comment by sanigo** [comment]
It is a better idea to convert kindle books to pdf using calibre than crack the device.

**Comment by yefeiyu** [comment]
Kindle no longer crashes when I turn off wifi.
I look forward to solving this problem as soon as possible.

**Comment by yefeiyu** [comment]
Today I installed Kindle 8.24, crashed.
[crashlogkindle.txt](https://github.com/HappyZ/dpt-tools/files/3817543/crashlogkindle.txt)

**Comment by whmzsu** [comment]
The newest version kindle apk not crash if you not login , or if you login but not stop the app or reboot. After boot or you force to stop the app, the next time when open the kindle ,it crashed .
